package vu.lt.mybatis.model;

public class Movie {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.MOVIE.ID
     *
     * @mbg.generated Thu Mar 26 20:51:42 EET 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.MOVIE.DURATION
     *
     * @mbg.generated Thu Mar 26 20:51:42 EET 2020
     */
    private String duration;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.MOVIE.NAME
     *
     * @mbg.generated Thu Mar 26 20:51:42 EET 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.MOVIE.YEAR
     *
     * @mbg.generated Thu Mar 26 20:51:42 EET 2020
     */
    private String year;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.MOVIE.PRODUCER_ID
     *
     * @mbg.generated Thu Mar 26 20:51:42 EET 2020
     */
    private Integer producerId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.MOVIE.ID
     *
     * @return the value of PUBLIC.MOVIE.ID
     *
     * @mbg.generated Thu Mar 26 20:51:42 EET 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.MOVIE.ID
     *
     * @param id the value for PUBLIC.MOVIE.ID
     *
     * @mbg.generated Thu Mar 26 20:51:42 EET 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.MOVIE.DURATION
     *
     * @return the value of PUBLIC.MOVIE.DURATION
     *
     * @mbg.generated Thu Mar 26 20:51:42 EET 2020
     */
    public String getDuration() {
        return duration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.MOVIE.DURATION
     *
     * @param duration the value for PUBLIC.MOVIE.DURATION
     *
     * @mbg.generated Thu Mar 26 20:51:42 EET 2020
     */
    public void setDuration(String duration) {
        this.duration = duration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.MOVIE.NAME
     *
     * @return the value of PUBLIC.MOVIE.NAME
     *
     * @mbg.generated Thu Mar 26 20:51:42 EET 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.MOVIE.NAME
     *
     * @param name the value for PUBLIC.MOVIE.NAME
     *
     * @mbg.generated Thu Mar 26 20:51:42 EET 2020
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.MOVIE.YEAR
     *
     * @return the value of PUBLIC.MOVIE.YEAR
     *
     * @mbg.generated Thu Mar 26 20:51:42 EET 2020
     */
    public String getYear() {
        return year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.MOVIE.YEAR
     *
     * @param year the value for PUBLIC.MOVIE.YEAR
     *
     * @mbg.generated Thu Mar 26 20:51:42 EET 2020
     */
    public void setYear(String year) {
        this.year = year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.MOVIE.PRODUCER_ID
     *
     * @return the value of PUBLIC.MOVIE.PRODUCER_ID
     *
     * @mbg.generated Thu Mar 26 20:51:42 EET 2020
     */
    public Integer getProducerId() {
        return producerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.MOVIE.PRODUCER_ID
     *
     * @param producerId the value for PUBLIC.MOVIE.PRODUCER_ID
     *
     * @mbg.generated Thu Mar 26 20:51:42 EET 2020
     */
    public void setProducerId(Integer producerId) {
        this.producerId = producerId;
    }
}