package vu.lt.mybatis.dao;

import java.util.List;
import vu.lt.mybatis.model.Producer;

public interface ProducerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PRODUCER
     *
     * @mbg.generated Thu Mar 26 20:51:42 EET 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PRODUCER
     *
     * @mbg.generated Thu Mar 26 20:51:42 EET 2020
     */
    int insert(Producer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PRODUCER
     *
     * @mbg.generated Thu Mar 26 20:51:42 EET 2020
     */
    Producer selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PRODUCER
     *
     * @mbg.generated Thu Mar 26 20:51:42 EET 2020
     */
    List<Producer> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PRODUCER
     *
     * @mbg.generated Thu Mar 26 20:51:42 EET 2020
     */
    int updateByPrimaryKey(Producer record);
}